language: node_js
sudo: false
node_js:
  - 8
cache:
  directories:
    - node_modules
install:
  - yarn
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
script:
  - yarn build
  - yarn test
  - yarn codecov
before_deploy:
  - touch .nojekyll