language: node_js
sudo: false
node_js:
  - lts/*
cache:
  yarn: true
  directories:
    - ~/.npm
    - .jest
    - node_modules
before_script:
  - yarn install --frozen-lockfile
install:
  - yarn
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
script:
  - yarn build
  - yarn test
  - yarn codecov
before_deploy:
  - touch .nojekyll